name: CI

on:
  push:
    branches:
      - main
      - lab-1
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y cmake clang clang-format clang-tidy

      - name: Run formatter
        run: clang-format -i source/**/*.cpp source/**/*.hpp

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Run tests
        run: echo "No tests implemented yet."
